config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
   get 'home/about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  has_one :userg
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:update, :edit, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build;
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friend_path, notice: "Not authorized to edit thies friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :birthday, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name%>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email%>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone%>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :birthday%>
    <%= form.date_field :birthday, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :address%>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.number_field :user_id, value:current_user.id, hidden: true %>
  </div>

  <div>
    <%= form.submit class: "btn btn-secondary" %>
    <%= link_to "Back", friends_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>" class="p-4 border text-white bg-secondary rounded">
  <h1>
    <%= friend.first_name + " " + friend.last_name %>
  </h1>

  <div class="row">
    <div class="col-md-6">
      <p>
        <strong>Email:</strong>
        <%= friend.email %>
      </p>
    </div>
    <div class="col-md-6">
      <p>
        <strong>Phone:</strong>
        <%= friend.phone %>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <p>
        <strong>Birthday:</strong>
        <%= friend.birthday %>
      </p>
    </div>
    <div class="col-md-6">
      <p>
        <strong>Address:</strong>
        <%= friend.address %>
      </p>
    </div>
  </div>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend <%= link_to "#{@friend.first_name + " " + @friend.last_name}", @friend%></h1>


<%= render "form", friend: @friend %>

app/views/friends/index.html.erb
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Birthday</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user_id == current_user.id %>
        <tr>
          <td><%= friend.id %></td>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.birthday %></td>
          <td><%= friend.address %></td>
          <td><%= link_to "Show", friend %></td>
          <td><%= link_to "Edit", edit_friend_path(friend) %></td>
          <td><%= link_to "Delete", friend, data: {"turbo-method": :delete} %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add friend</h1>
<%= render "form", friend: @friend %>

app/views/friends/show.html.erb
<%= render @friend %>

<div class="mt-4">
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary"%>
  <%= link_to "Back", friends_path, class:"btn btn-secondary" %>
  <td><%= link_to "Delete", @friend, data: {
    "turbo-method": :delete,
    "turbo-confirm": "Are you sure?"
  }, class:"btn btn-secondary" %></td>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand">
    <img src=<%= asset_path('logo.png') %> width="30" height="30" alt="">
  </a>

  <%= link_to 'Ruby Friends', root_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About", home_about_path, class:"nav-link" %>
      </li>
      <% unless user_signed_in? %>
        <li>
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>
        <li>
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
        </li>
      <%  end %>

      <% if user_signed_in? %>
        <li>
          <%= link_to 'Show Friends', friends_path, class:"nav-link" %>
        </li>
        <li>
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>
        <li>
          <%= link_to 'Sign Out', destroy_user_session_path, data: {"turbo_method": :delete}, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">About this website</h1>
    <p class="lead">Educational purpose website for testing Ruby on Rails!</p>
    <img src=<%= asset_path('Ruby_On_Rails_Logo.svg.png')%> width="265" height="100" class="mr-5">
    <img src=<%= asset_path('Bootstrap_logo.svg.png')%> width="125" height="100">
    <hr class="my-4">
    <p>Created by Vladyslav Liubchyk</p>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">Ruby friends</h1>
    <p class="lead">Add friends to your list, to not forget theirs important data such as birthday or phone number!</p>
    <hr class="my-4">
    <div class="d-flex">
      <%= link_to "Get Started", new_user_registration_path, class: "btn btn-secondary mr-2" %>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Ruby Friends</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <%= if notice
              render 'layouts/alert'
          end %>

      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>